#!/usr/bin/env python3
"""Generate both BIOS payload implementations from the restricted Z80 source."""
import argparse
from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[1]

def generate():
    source = (ROOT/'transport/payload.z80').read_text()
    asm = source.replace('    @STORE@', ' ifdef MSXPI_DRIVER\n    call STORE_BYTE\n else\n    ld (de),a\n endif')
    # Reuse the DOS kernel's existing alignment holes without moving entry points.
    rx, rest = asm.split('PAYLOAD_TX:\n', 1)
    tx, rest = ('PAYLOAD_TX:\n'+rest).split('; A is the completed byte.', 1)
    advance_wait, escape = ('; A is the completed byte.'+rest).split('PAYLOAD_ESCAPE:\n', 1)
    # Keep ESC's comments with the preceding fragment; labels define the split.
    escape = 'PAYLOAD_ESCAPE:\n'+escape
    pieces = {'payload_tx_generated.asm': tx,
              'payload_wait_generated.asm': advance_wait,
              'payload_escape_generated.asm': escape}
    asm = rx + ' ifdef MSXPI_PAYLOAD_ROM_SPLIT\n else\n' + ''.join(pieces.values()) + ' endif\n'
    c = source.replace('    @STORE@', '    ld (de),a')
    # SDAS needs # on immediate operands, but not branch labels or port numbers.
    lines = []
    for line in c.splitlines():
        if re.match(r'\s*(ld|cp|and|or)\s', line):
            line = re.sub(r'(?<=[ ,])(0x[0-9a-f]+|[0-9]+)$', r'#\1', line)
        lines.append(line)
    c = '\n'.join(lines)
    adapters = []
    for direction in ('RX', 'TX'):
        adapters.append(f'''static uint8_t payload_{direction.lower()}(uint8_t *buffer, uint16_t count,
                                  uint16_t *sum) __naked
{{
    buffer; count; sum;
    __asm
    push ix
    ld ix,#4
    add ix,sp
    ld e,0(ix)
    ld d,1(ix)
    ld c,2(ix)
    ld b,3(ix)
    ld hl,#0
    call PAYLOAD_{direction}
    ; Save status before arithmetic or pointer setup can change flags.
    ld a,#0xe0
    jr nc,payload_{direction.lower()}_ok
    ld a,#0xe2
payload_{direction.lower()}_ok:
    ld c,4(ix)
    ld b,5(ix)
    push af
    ld a,l
    ld (bc),a
    inc bc
    ld a,h
    ld (bc),a
    pop af
    ld l,a
    pop ix
    ret
    __endasm;
}}
''')
    header = ('/* Generated by transport/generate.py; edit payload.z80. */\n'
              'static void payload_kernel(void) __naked {\n    __asm\n' + c +
              '\n    __endasm;\n}\n' + '\n'.join(adapters))
    result = {ROOT/'asm-common/include/payload_generated.asm': '; Generated by transport/generate.py\n'+asm,
            ROOT/'C-common/lib/payload_generated.h': header}
    result.update({ROOT/'asm-common/include'/name: '; Generated by transport/generate.py\n'+body for name, body in pieces.items()})
    return result

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args=parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text()!=content:
                raise SystemExit(f'Stale generated file: {path}')
        else:
            path.write_text(content)
if __name__=='__main__': main()
