; Generated by transport/generate.py
PAYLOAD_TX:
    ld a,b
    or c
    ret z
PAYLOAD_TX_LOOP:
    ld a,c
    or a
    call z,PAYLOAD_ESCAPE
    ret c
    call PAYLOAD_WAIT
    ret c
    ld a,(de)
    out (0x5a),a
    call PAYLOAD_ADVANCE
    jr nz,PAYLOAD_TX_LOOP
    ret
