; Generated by transport/generate.py
; A is the completed byte. NZ=count remains, CF=0 on completion.
PAYLOAD_ADVANCE:
    add a,l
    ld l,a
    jr nc,PAYLOAD_NO_CARRY
    inc h
PAYLOAD_NO_CARRY:
    inc de
    dec bc
    ld a,b
    or c
    ret
; Fast ready path changes AF only. Slow path checks ESC every 256 polls.
PAYLOAD_WAIT:
    in a,(0x56)
    or a
    ret z
    cp 2
    ret z
    push bc
    ld b,0
PAYLOAD_WAIT_SLOW:
    in a,(0x56)
    or a
    jr z,PAYLOAD_WAIT_DONE
    cp 2
    jr z,PAYLOAD_WAIT_DONE
    djnz PAYLOAD_WAIT_SLOW
    call PAYLOAD_ESCAPE
    jr c,PAYLOAD_WAIT_DONE
    jr PAYLOAD_WAIT_SLOW
PAYLOAD_WAIT_DONE:
    pop bc
    ret
; Preserve row selection, upper PPI bits and the incoming interrupt state.
; No BIOS call: safe with interrupts disabled, no reliance on BSS.
