; Generated by transport/generate.py
PAYLOAD_ESCAPE:
    push bc
    ld a,i
    push af
    di
    in a,(0xaa)
    ld b,a
    and 0xf0
    or 7
    out (0xaa),a
    in a,(0xa9)
    ld c,a
    ld a,b
    out (0xaa),a
    pop af
    jp po,PAYLOAD_ESCAPE_IFF_OFF
    ei
PAYLOAD_ESCAPE_IFF_OFF:
    ld a,c
    pop bc
    and 4
    ret nz
    ld a,0xe2
    scf
    ret
