; Generated by transport/generate.py
; Canonical Z80 payload kernel. Generated for zmac and SDCC by generate.py.
; DE=buffer, BC=count, HL=16-bit running sum. Preserves IX/IY and shadows.
; CF error: A=RC_ESCPRESSED, DE/BC/HL describe completed bytes only.
; Polled mode: caller owns link and leaves /WAIT off (UNAPI ETH_END does so).
PAYLOAD_RX:
    ld a,b
    or c
    ret z
    in a,(0x57)
    cp 0xfe
    jp nc,PAYLOAD_RX_TCP
PAYLOAD_RX_PI:
    ld a,c
    or a
    call z,PAYLOAD_ESCAPE
    ret c
    call PAYLOAD_WAIT
    ret c
    xor a
    out (0x56),a
    call PAYLOAD_WAIT
    ret c
    in a,(0x5a)
 ifdef MSXPI_DRIVER
    call STORE_BYTE
 else
    ld (de),a
 endif
    call PAYLOAD_ADVANCE
    jr nz,PAYLOAD_RX_PI
    ret
PAYLOAD_RX_TCP:
    ld a,c
    or a
    call z,PAYLOAD_ESCAPE
    ret c
    call PAYLOAD_WAIT
    ret c
    xor a
    out (0x56),a
PAYLOAD_RX_TCP_WAIT:
    call PAYLOAD_WAIT
    ret c
    cp 2
    jr z,PAYLOAD_RX_TCP_GOT
    call PAYLOAD_ESCAPE
    ret c
    jr PAYLOAD_RX_TCP_WAIT
PAYLOAD_RX_TCP_GOT:
    in a,(0x5a)
 ifdef MSXPI_DRIVER
    call STORE_BYTE
 else
    ld (de),a
 endif
    call PAYLOAD_ADVANCE
    jr nz,PAYLOAD_RX_TCP
    ret
 ifdef MSXPI_PAYLOAD_ROM_SPLIT
 else
PAYLOAD_TX:
    ld a,b
    or c
    ret z
PAYLOAD_TX_LOOP:
    ld a,c
    or a
    call z,PAYLOAD_ESCAPE
    ret c
    call PAYLOAD_WAIT
    ret c
    ld a,(de)
    out (0x5a),a
    call PAYLOAD_ADVANCE
    jr nz,PAYLOAD_TX_LOOP
    ret
; A is the completed byte. NZ=count remains, CF=0 on completion.
PAYLOAD_ADVANCE:
    add a,l
    ld l,a
    jr nc,PAYLOAD_NO_CARRY
    inc h
PAYLOAD_NO_CARRY:
    inc de
    dec bc
    ld a,b
    or c
    ret
; Fast ready path changes AF only. Slow path checks ESC every 256 polls.
PAYLOAD_WAIT:
    in a,(0x56)
    or a
    ret z
    cp 2
    ret z
    push bc
    ld b,0
PAYLOAD_WAIT_SLOW:
    in a,(0x56)
    or a
    jr z,PAYLOAD_WAIT_DONE
    cp 2
    jr z,PAYLOAD_WAIT_DONE
    djnz PAYLOAD_WAIT_SLOW
    call PAYLOAD_ESCAPE
    jr c,PAYLOAD_WAIT_DONE
    jr PAYLOAD_WAIT_SLOW
PAYLOAD_WAIT_DONE:
    pop bc
    ret
; Preserve row selection, upper PPI bits and the incoming interrupt state.
; No BIOS call: safe with interrupts disabled, no reliance on BSS.
PAYLOAD_ESCAPE:
    push bc
    ld a,i
    push af
    di
    in a,(0xaa)
    ld b,a
    and 0xf0
    or 7
    out (0xaa),a
    in a,(0xa9)
    ld c,a
    ld a,b
    out (0xaa),a
    pop af
    jp po,PAYLOAD_ESCAPE_IFF_OFF
    ei
PAYLOAD_ESCAPE_IFF_OFF:
    ld a,c
    pop bc
    and 4
    ret nz
    ld a,0xe2
    scf
    ret
 endif
