#!/bin/bash

export buildClientCommands="yes"
export buildBIOS="yes"
export buildOpenMSXConfig="yes"
export buildMSXdiskImage="yes"
export updateVersions="NO"

XMLPATH=openMSX/share/extensions
OPENMSXSRC=../../openMSX/openMSX
export HOME=../../../..
export BIOS=ROM/src/BIOS/msxpibios.asm
export ROMBANK1=$HOME/Dev/MSX/gameroms/ROAD.ROM
export BIOSFILE=target/msxpidos.rom
export ZMAC_PATH=$HOME/Dev/zmac
export HEX2BIN_PATH=$HOME/Dev/bin
export Z80ASM_PATH=$HOME/Dev/z80asm-1.8
export ZCCCFG=/cygdrive/c/Apps/z88dk-win32-2.3/lib/config
export OPENMSXDISK=$HOME/Desktop/MSXPi/commands
export GITPATH=https://github.com/costarc/MSXPi/raw/master/software

MSXPIHOME=/home/pi/msxpi
export PI=raspberrypi

# Functions
UpdateBuildId() {
	if [ $updateVersions = "yes" ];then
		fname=$1
		cp $fname $fname.bak
		curdefine=$(cat $fname | grep "^BuildId = ")
		today=$(date +%Y%m%d)
		newbuild=$(cat $fname | grep "BuildId = " | awk '{print $3}' | cut -f2 -d"."|sed 's/"//'|awk '{printf "%03d\n", $1 + 1;}')
		rc=$?
        if [ "$rc" = 0 ]; then
            newdefine="BuildId = \"${today}.${newbuild}\""
            # Escape special characters in $curdefine for literal match
            esc_curdefine=$(printf '%s\n' "$curdefine" | sed 's/[.[\*^$/]/\\\\&/g')
            sed "s|$esc_curdefine|$newdefine|" "$fname" > "$fname.tmp" && mv "$fname.tmp" "$fname"
            echo "New BuildId for $1: $today.$newbuild"
        fi
	fi
}

# Functionsf
UpdateBuildIdASM() {
    if [ "$updateVersions" = "yes" ]; then
        fname="$1"
        cp "$fname" "$fname.bak"
    
        # Get the last BuildId line
        curdefine=$(grep "^BuildId: DB" "$fname" | tail -n 1)
    
        # Extract and increment the build number
        today=$(date +%Y%m%d)
        lastbuild=$(echo "$curdefine" | sed -n 's/.*"\.[0-9]\{8\}\.\([0-9]\{3\}\)".*/\1/p')
        newbuild=$(printf "%03d\n" $((10#$lastbuild + 1)))
        rc=$?
    
        if [ "$rc" = 0 ]; then
            newdefine="BuildId: DB \".${today}.${newbuild}\""
            esc_curdefine=$(printf '%s\n' "$curdefine" | sed 's/[.[\*^$/]/\\\\&/g')
            sed "s|$esc_curdefine|$newdefine|" "$fname" > "$fname.tmp" && mv "$fname.tmp" "$fname"
            echo "New BuildId for $1: .${today}.${newbuild}"
        fi
    fi
}

genUpdateBatch() {
  echo "echo Preparing to update..." >> /tmp/msxpiupd.bat
  echo "pset DriveM ${GITPATH}/target"  >> /tmp/msxpiupd.bat
  echo "pdate" >> /tmp/msxpiupd.bat
  echo "echo Getting lastest updater..." >> /tmp/msxpiupd.bat
  echo "pcopy m:msxpirfh.bat" >> /tmp/msxpiupd.bat
  echo "pcopy m:msxpiupd.bat" >> /tmp/msxpiupd.bat
  echo "echo "  >> /tmp/msxpiupd.bat
  echo "echo Starting update" >> /tmp/msxpiupd.bat
  echo "msxpirfh" >> /tmp/msxpiupd.bat
  
  rm target/msxpirfh.bat  > /dev/null 2>&1
    
  for fn in `ls target | grep -v -i pcopy.com`
  do
    if [ -f target/${fn} ];then
      echo "pcopy m:${fn}" >> /tmp/msxpirfh.bat
    fi
  done
  echo "pcopy m:pcopy.com" >> /tmp/msxpirfh.bat
  
  echo "echo  " >> /tmp/msxpirfh.bat
  echo "pcd /home/pi/msxpi" >> /tmp/msxpirfh.bat
  echo "prun wget -q -O msxpi-server.py https://tinyurl.com/msxpi-server"  >> /tmp/msxpirfh.bat
  echo "echo "  >> /tmp/msxpirfh.bat
  echo "echo Restarting msxpi-server.py" >> /tmp/msxpirfh.bat
  echo "prestart" >> /tmp/msxpirfh.bat
  echo "pver" >> /tmp/msxpirfh.bat
  perl -pe 's/\r?\n/\r\n/' /tmp/msxpiupd.bat > target/msxpiupd.bat
  perl -pe 's/\r?\n/\r\n/' /tmp/msxpirfh.bat > target/msxpirfh.bat
  rm /tmp/msxpiupd.bat
  rm /tmp/msxpirfh.bat 
}

# MSX-Dos P Commands
if [ $buildClientCommands = "yes" ];then
  echo "Compiling MSXPi DOS Commands"
  #$Z80ASM_PATH/z80asm.exe -I ./asm-common/include ./Client/src/template.com.asm -o ./target/template.com
  #$Z80ASM_PATH/z80asm.exe -I ./asm-common/include ./Client/src/pcopy.com.asm    -o ./target/pcopy.com
  #$Z80ASM_PATH/z80asm.exe -I ./asm-common/include ./Client/src/at28c256.com.asm -o ./target/at28c256.com
fi

if [ $buildBIOS = "yes" ];then
  echo "Compiling MSXPi BIOS and MSX-DOS ROM"

  # Bump BuildIds BEFORE compiling, not after - msx-dos.mac includes
  # msxpi-driver.mac, so the id must already be updated in the source
  # before zmac runs, or the compiled ROM bakes in the previous run's id
  # and the bump only takes effect on the *next* build.
  UpdateBuildIdASM ./ROM/src/MSX-DOS/msxpi-driver.mac
  UpdateBuildIdASM ./ROM/src/BIOS/msxpibios.asm
  UpdateBuildIdASM ./ROM/src/BIOS/msxpiext.asm
  UpdateBuildId    ./Server/Python/src/msxpi-server.py

  $ZMAC_PATH/zmac.exe -I ./asm-common/include -I ./ROM/src/MSX-DOS ./ROM/src/MSX-DOS/msx-dos.mac

  # Build MSX-DOS Driver
  [ -f ./zout/msx-dos.hex ] && $HEX2BIN_PATH/hex2bin.exe -s 4000 ./zout/msx-dos.hex && cp ./zout/msx-dos.bin ./target/msxpidos.rom
  
  # Build BIOS
  #$Z80ASM_PATH/z80asm.exe -I ./asm-common/include ./ROM/src/BIOS/msxpibios.asm  -o ./target/msxpbios.rom
  
  # Build BASIC BIOS Extension
  #$Z80ASM_PATH/z80asm.exe -I ./asm-common/include ./ROM/src/BIOS/msxpiext.asm   -o ./target/msxpiext.bin

  # Create an optional 2-bank ROMs for the EEPROM
  
  #cat $ROMBANK1 > target/multirom.rom
  #cat $BIOSFILE >> target/multirom.rom
fi

if [ $buildOpenMSXConfig = "yes" ];then
  # do not replace the msxpibios on every build to avoid users having to update their bios/sha constantly
  SHA=$(sha1sum $BIOSFILE | cut -f1 -d" ")
  sed "s/msxpibiossha/$SHA/" MSXPi.xml.template > $XMLPATH/MSXPi.xml
  cp $BIOSFILE openMSX/share/systemroms/extensions/msxpidos.rom
  cp $BIOSFILE          ../../../../Documents/openMSX/share/systemroms/extensions/msxpidos.rom
  cp $XMLPATH/MSXPi.xml ../../../../Documents/openMSX/share/extensions/MSXPi.xml
  # Update sources for openMSX extensions - to keep up to date with openMSX fork
  cp $OPENMSXSRC/src/MSXPiDevice.cc         openMSX/src/MSXPiDevice.cc
  cp $OPENMSXSRC/src/MSXPiDevice.hh         openMSX/src/MSXPiDevice.hh
  cp $OPENMSXSRC/src/DeviceFactory.cc       openMSX/src/DeviceFactory.cc
  cp $OPENMSXSRC/build/msvc/openmsx.vcxproj openMSX/build/msvc/openmsx.vcxproj
fi

if [ $buildMSXdiskImage = "yes" ];then
  genUpdateBatch
  # Generate msxpiboot.dsk disk image
  python3 dsktool.py format target/disks/msxpiboot.dsk
  python3 dsktool.py format target/disks/tools.dsk
  python3 dsktool.py copy "target/disks/MSXDOS.SYS"  "target/disks/msxpiboot.dsk:MSXDOS.SYS"
  python3 dsktool.py copy "target/disks/COMMAND.COM" "target/disks/msxpiboot.dsk:COMMAND.COM"
  python3 dsktool.py copy "target/msxpidos.rom" "target/disks/msxpiboot.dsk:MSXPIDOS.ROM"

  # LOADROM.COM (the MSXPi network-loading patch of LOADROM.COM v1.97 -
  # see Client/src/loadrom/README.md) lives under Client/src/loadrom/,
  # not target/ like every other client .com - stage it into target/
  # first so the glob below picks it up like everything else.
  cp Client/src/loadrom/LOADROM.COM target/LOADROM.COM

  for file in `ls target/*.com target/*.COM target/*.BAS target/*.ini`
  do
    fname="${file##*/}"
    [ -f $file ] && python3 dsktool.py copy "$file" "target/disks/msxpiboot.dsk:$fname"
  done

  echo "Copying disk images to /home/pi/msxpi/disks/"
  cp target/disks/msxpiboot.dsk /c/home/pi/msxpi/disks/
  cp target/disks/tools.dsk /c/home/pi/msxpi/disks/
fi

