#!/bin/bash
set -x
# 2017-11-23 : Added ramdisk setup
# 2017-11-18 : Added switch to python or C version

MSXPIHOME=/home/msxpi
FILELIST="senddatablock.msx uploaddata.msx secsenddata.msx ploadbin.msx pplay.sh pshut.sh"
USEROOT=$(/usr/bin/whoami | /bin/grep -c "root")

if [[ $USEROOT -eq 1 ]];then
    PREFIX="sudo -i -u pi "
    OSCMDPREFIX=
else
    PREFIX=
    OSCMDPREFIX="sudo "
fi

sudo kill -9 $(ps -ef | grep 'python /home/msxpi/msxpi-server.py' | grep -v grep  | awk '{print $2}')

msxpisrv=$(grep -c "Server=C" ${MSXPIHOME}/msxpi.ini)
if [[ $msxpisrv -eq 1 ]];then
    MSXPISERVER="sudo $MSXPIHOME/msxpi-server"
else
    MSXPISERVER="/usr/bin/python $MSXPIHOME/msxpi-server.py"
fi

# check if msxpi files are already installed in ramdisk
if [[ ! -e /media/ramdisk/senddatablock.msx ]]; then
    if [[ $(/bin/df /media/ramdisk | /bin/grep -c ramdisk) -eq 0 ]]; then
        if [[ ! -e /media/ramdisk/ ]]; then
            ${OSCMDPREFIX}mkdir /media/ramdisk
        fi
        echo y | ${OSCMDPREFIX}/sbin/mke2fs -q -m 0 /dev/ramdisk 1m
        ${OSCMDPREFIX}/bin/mount /dev/ramdisk /media/ramdisk
        ${OSCMDPREFIX}chown pi.pi /media/ramdisk
    fi
fi

for file in $FILELIST
do
    cp -p $MSXPIHOME/$file /media/ramdisk/
done

R=$(echo $1 | /bin/grep -c "\-t")
if [[ $# -eq 1 && $R -eq 1 ]]; then
    echo "Entering test mode"
    $MSXPISERVER
    exit 0
fi

echo "Restarting msxpi-server"
$MSXPISERVER &

rm /home/pi/msxpi/msxpi-update*

while :
do
sleep 5
state=$(ps -ef | grep msxpi-server | grep  -v grep | wc -l)

if [[ $state -eq 0 ]];then
    msxpid=$(ps -ef | grep msxpi-server | grep -v "grep" | awk '{print $2}')
    msxpid="$msxpid 99999"
    echo "killing $msxpid"
    set $msxpid 
    if [[ $# -gt 1 ]];then
        kill -9 $msxpid
    fi

    echo "Restarting msxpi-server"
    msxpisrv=$(grep -c "Server=C" ${MSXPIHOME}/msxpi.ini)
    if [[ msxpisrv -eq 1 ]];then
        ${MSXPIHOME}/msxpi-server &
    else
        /usr/bin/python ${MSXPIHOME}/msxpi-server.py &
    fi
    sleep 1
    msxpid=$(ps -ef | grep msxpi-server | grep -v "grep" | awk '{print $2}')
    msxpid="$msxpid 99999"
    set $msxpid 
    if [[ $# -gt 1 ]];then
        kill -9 $msxpid
    fi
    if [[ msxpisrv -eq 1 ]];then
        ret=$(${MSXPIHOME}/msxpi-server 2>&1 &)
    else
        ret=$(/usr/bin/python ${MSXPIHOME}/msxpi-server.py 2>&1 &)
    fi
    if [[ `echo $ret | grep -c "initialisation failed"` -eq 1 ]];then
        shutdown -h now
    fi
fi

# whatsup server

wupsvc=$(grep -c "1" /media/ramdisk/whatsup.state)
if [[ $wupsvc -eq 1 ]];then
    wupph=$(cat /media/ramdisk/wup.config|cut -f1 -d" ")
    wuppw=$(cat /media/ramdisk/wup.config|cut -f2 -d" ")
    rm /media/ramdisk/wup.config
    wuptst=$(echo $wuppw | wc -c)
    if [[ $wuptst -gt 10 ]];then
        sudo echo > /media/ramdisk/chat-session.log
        /usr/bin/python /home/pi/yowsup/run.py ${wupph} ${wuppw} &
        echo "2" > /media/ramdisk/whatsup.state
    else
       echo "WhatsUp service failed to start"
    fi
fi
wupsvc=$(grep -c "3" /media/ramdisk/whatsup.state)
if [[ $wupsvc -eq 1 ]];then
    sudo kill -9 $(ps -ef | grep 'python /home/pi/yowsup/run.py' | grep -v grep  | awk '{print $2}')
    echo "0" > /media/ramdisk/whatsup.state
fi
done


